[build]
builder = "nixpacks"

[build.nixpacks]
# Install Python dependencies
beforeBuild = "pip3 install -r server/requirements.txt"

[deploy]
startCommand = "node server/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/health"
healthcheckTimeout = 100

PORT = "5176"

