[build]
builder = "nixpacks"

[deploy]
startCommand = "node server/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[build.nixpacks.phase]]
name = "install-python-deps"
cmds = ["pip3 install -r server/requirements.txt"]
